### ISSUE TITLE
crash when defining experiment type

### ISSUE THREAD

**Issue by axd6** [Dionne-Lab/catalight#11]
Looks like a wavelength setting was recently added in the code but not the GUI

Steps to reproduce crash:
- Start up Catalight GUI
- Add an Experiment
- Select the newly added experiment
- In the Experiment Design tab, change the experiment type to any other type from undefined

This error does not happen if the experiment type is changed when no experiment in Study Overview is selected.

Console output:
Traceback (most recent call last):
  File "C:\src\repos\catalight\catalight\catalight_GUI.py", line 569, in update_expt
    expt._update_expt_name()  # autoname experiment
  File "C:\src\repos\catalight\catalight\equipment\experiment_control.py", line 504, in _update_expt_name
    str(self.wavelength[0]),
TypeError: 'NoneType' object is not subscriptable

**Comment by Briley645** [comment]
This issue was called because expt name is currently being defined w/o naming a wavelength when using the GUI (wavelength not yet implemented into GUI). The default value for expt.wavelength was "None" and changing it to "[None]" fixed the indexing issue.
